branch-defaults:
  main:
    environment: Tsgallerybeanstalk-env-1
deploy:
  artifact: ts_gallery.zip
global:
  application_name: TsgalleryBeanstalk
  branch: main
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  repository: https://github.com/tutugodfrey/ts_gallery.git
  sc: git
  profile: ebcli
  workspace_type: Application
